version: 2.1

jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify

  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=release

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=release

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=debug

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=debug

  x86-64-unknown-linux-nightly:
    docker:
      - image: ponylang/ponyup-ci-nightly-builder:latest
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-nightly.bash ${CLOUDSMITH_API_KEY}

  cut-release:
    docker:
      - image: ponylang/shared-docker-ci-release-a-library:release
    steps:
      - checkout
      - run: bash .ci-scripts/release.bash "$CIRCLE_TAG" "$GITHUB_TOKEN" "$ZULIP_TOKEN"

  build-release:
    docker:
      - image: ponylang/shared-docker-ci-release-a-library:release
    steps:
      - checkout
      - run: bash .ci-scripts/ "$CIRCLE_TAG" "$GITHUB_TOKEN"

workflows:
  version: 2.1

  pr-acceptance-tests:
    jobs:
      - verify-changelog:
          filters:
            branches:
              ignore:
                - master
      - release-vs-ponyc-release:
          filters:
            branches:
              ignore:
                - master
      - debug-vs-ponyc-release:
          filters:
            branches:
              ignore:
                - master

  daily-check-for-breakage:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master
      - debug-vs-ponyc-master

  create-and-upload-nightly-release:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - x86-64-unknown-linux-nightly:
          context: org-global

  create-release:
    jobs:
      - cut-release:
          filters:
            tags:
              only: /^release-\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

  on-release-being-tagged:
    jobs:
      - generate-documentation-pr-for-main-dot-actor:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

