version: 2.1

jobs:
  verify-changelog:
    docker:
      - image: ponylang/changelog-tool:release
    steps:
      - checkout
      - run: changelog-tool verify

  release-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=release

  release-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=release

  debug-vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make test config=debug

  debug-vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make test config=debug

  x86-64-unknown-linux-nightly:
    docker:
      - image: ponylang/ponyup-ci-nightly-builder:latest
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-nightly.bash ${CLOUDSMITH_API_KEY}

  x86-64-unknown-linux-release:
    docker:
      - image: ponylang/ponyup-ci-nightly-builder:latest
    steps:
      - checkout
      - run: bash .ci-scripts/x86-64-unknown-linux-release.bash ${CLOUDSMITH_API_KEY}

  cut-release:
    docker:
      - image: ponylang/shared-docker-ci-release-a-library:release
    steps:
      - checkout
      - run: bash .ci-scripts/release.bash "$CIRCLE_TAG" "$GITHUB_TOKEN" "$ZULIP_TOKEN"

  build-release:
    docker:
      - image: ponylang/shared-docker-ci-release-a-library:release
    steps:
      - checkout
      - run: bash .ci-scripts/ "$CIRCLE_TAG" "$GITHUB_TOKEN"

  build-latest-docker-image:
      docker:
        - image: ponylang/shared-docker-ci-docker-builder:20190808
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
        - run: docker build --file=Dockerfile -t {%%DOCKER_REPO%%}:latest .
        - run: docker push {%%DOCKER_REPO%%}:latest

  build-release-docker-image:
      docker:
        - image: ponylang/shared-docker-ci-docker-builder:20190808
      steps:
        - checkout
        - setup_remote_docker
        - run: docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
        - run: bash build-docker-images-on-release.bash "$CIRCLE_TAG"

workflows:
  version: 2.1

  pr-acceptance-tests:
    jobs:
      - verify-changelog:
          filters:
            branches:
              ignore:
                - master
      - release-vs-ponyc-release:
          filters:
            branches:
              ignore:
                - master
      - debug-vs-ponyc-release:
          filters:
            branches:
              ignore:
                - master

  daily-check-for-breakage:
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only: master
    jobs:
      - release-vs-ponyc-master
      - debug-vs-ponyc-master

  create-and-upload-nightly-release:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - x86-64-unknown-linux-nightly:
          context: org-global

  create-release:
    jobs:
      - cut-release:
          filters:
            tags:
              only: /^release-\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

  create-and-upload-release:
    jobs:
      - x86-64-unknown-linux-release:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/

  # Docker `latest` image building
  build-latest-docker-image:
    jobs:
      - build-latest-docker-image:
          filters:
            branches:
              only:
                - master

  # Build docker images on release
  # We don't need to build `latest` here as there's another commit
  # to master immediately after release gets kicked off that will pick
  # up all the meaningful changes. Only the TAG will be missing.
  build-release-docker-image:
    jobs:
      - build-release-docker-image:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
